Fixed java.lang.RuntimeException when not logged in
java.lang.RuntimeException: Unable to start receiver
de.hfu.studiportal.network.RefreshTaskStarter:
android.util.AndroidRuntimeException: Calling startActivity() from
outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK
flag. Is this really what you want?
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2617)
at android.app.ActivityThread.access$1800(ActivityThread.java:147)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5260)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.ja
va:898)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
Caused by: android.util.AndroidRuntimeException: Calling
startActivity() from outside of an Activity context requires the
FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
at android.app.ContextImpl.startActivity(ContextImpl.java:1249)
at android.app.ContextImpl.startActivity(ContextImpl.java:1236)
at android.content.ContextWrapper.startActivity(ContextWrapper.java:322)
at android.content.ContextWrapper.startActivity(ContextWrapper.java:322)
at
de.hfu.studiportal.network.RefreshTaskStarter.startRefreshTask(RefreshTa
skStarter.java:63)
at
de.hfu.studiportal.network.RefreshTaskStarter.onReceive(RefreshTaskStart
er.java:34)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2610)
... 9 more